version: '3.1'
services:
  app:
    container_name: note-box-service
    build: ./note-box-service
    ports:
      - "6000:6000"
    depends_on:
      - dbpostgresql
  dbpostgresql:
    image: postgres
    ports:
      - "5432:5432"
    restart: always
    environment:
      - POSTGRES_PASSWORD=admin123
      - POSTGRES_USER=postgres
      - POSTGRES_DB=notebox-db