server:
  port: 6000

spring:
  datasource:
    url: jdbc:postgresql://localhost/notebox-db
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: admin123
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: create